// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/eventia-config/ScrollElegant.tsx": () => import("../components/mockups/eventia-config/ScrollElegant.tsx"),
  "./components/mockups/eventia-config/WizardEtapes.tsx": () => import("../components/mockups/eventia-config/WizardEtapes.tsx"),
  "./components/mockups/eventia-dashboard/MacWindowDark.tsx": () => import("../components/mockups/eventia-dashboard/MacWindowDark.tsx"),
  "./components/mockups/eventia-dashboard/StudioOpera.tsx": () => import("../components/mockups/eventia-dashboard/StudioOpera.tsx"),
  "./components/mockups/eventia-invitation/CinemaImmersif.tsx": () => import("../components/mockups/eventia-invitation/CinemaImmersif.tsx"),
  "./components/mockups/eventia-invitation/LuxeDefile.tsx": () => import("../components/mockups/eventia-invitation/LuxeDefile.tsx"),
  "./components/mockups/eventia-landing/CinematiqueSombre.tsx": () => import("../components/mockups/eventia-landing/CinematiqueSombre.tsx"),
  "./components/mockups/eventia-landing/IvoireEditorial.tsx": () => import("../components/mockups/eventia-landing/IvoireEditorial.tsx"),
  "./components/mockups/eventia-rsvp/ConversationIntime.tsx": () => import("../components/mockups/eventia-rsvp/ConversationIntime.tsx"),
  "./components/mockups/eventia-rsvp/FormulaireLuxe.tsx": () => import("../components/mockups/eventia-rsvp/FormulaireLuxe.tsx"),
  "./components/mockups/eventia-std/CompteARebours.tsx": () => import("../components/mockups/eventia-std/CompteARebours.tsx"),
  "./components/mockups/eventia-std/ScratchDore.tsx": () => import("../components/mockups/eventia-std/ScratchDore.tsx"),
  "./components/mockups/eventia-site/EditoralePure.tsx": () => import("../components/mockups/eventia-site/EditoralePure.tsx"),
  "./components/mockups/eventia-site/MaisonCinematique.tsx": () => import("../components/mockups/eventia-site/MaisonCinematique.tsx"),
  "./components/mockups/eventia-site/SignaturePrecieuse.tsx": () => import("../components/mockups/eventia-site/SignaturePrecieuse.tsx")
};
