/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoilesRouteImport } from './routes/voiles'
import { Route as UnionRouteImport } from './routes/union'
import { Route as SurMesureRouteImport } from './routes/sur-mesure'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SaveTheDateRouteImport } from './routes/save-the-date'
import { Route as PortesRouteImport } from './routes/portes'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as OffresRouteImport } from './routes/offres'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as EntreprisesRouteImport } from './routes/entreprises'
import { Route as EcrinsRouteImport } from './routes/ecrins'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfigurateurRouteImport } from './routes/configurateur'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ComparerRouteImport } from './routes/comparer'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SaveTheDateIndexRouteImport } from './routes/save-the-date.index'
import { Route as StudioSlugRouteImport } from './routes/studio.$slug'
import { Route as SaveTheDateFormatRouteImport } from './routes/save-the-date.$format'
import { Route as RsvpTokenRouteImport } from './routes/rsvp.$token'
import { Route as MaCommandeRefRouteImport } from './routes/ma-commande.$ref'
import { Route as LiveTokenRouteImport } from './routes/live.$token'
import { Route as InvitationTokenRouteImport } from './routes/invitation.$token'
import { Route as GalerieTokenRouteImport } from './routes/galerie.$token'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences.$slug'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AuthenticatedMesInvitationsRouteImport } from './routes/_authenticated/mes-invitations'
import { Route as AuthenticatedMesCommandesRouteImport } from './routes/_authenticated/mes-commandes'
import { Route as AuthenticatedDecorationsRouteImport } from './routes/_authenticated/decorations'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicWeddingRemindersRouteImport } from './routes/api/public/wedding-reminders'
import { Route as ApiPublicStatusTransitionRouteImport } from './routes/api/public/status-transition'
import { Route as ApiPublicRsvpRemindersRouteImport } from './routes/api/public/rsvp-reminders'
import { Route as ApiPublicGumroadRouteImport } from './routes/api/public/gumroad'
import { Route as ApiPublicEmailWorkerRouteImport } from './routes/api/public/email-worker'
import { Route as AuthenticatedStudioIdRouteImport } from './routes/_authenticated/studio.$id'
import { Route as AuthenticatedAdminInvitationsRouteImport } from './routes/_authenticated/admin/invitations'
import { Route as AuthenticatedAdminCommandesRouteImport } from './routes/_authenticated/admin/commandes'
import { Route as AuthenticatedAdminB2bRouteImport } from './routes/_authenticated/admin/b2b'
import { Route as AuthenticatedAdminAteliersRouteImport } from './routes/_authenticated/admin/ateliers'
import { Route as AuthenticatedMesInvitationsIdLiveRouteImport } from './routes/_authenticated/mes-invitations.$id.live'

const VoilesRoute = VoilesRouteImport.update({
  id: '/voiles',
  path: '/voiles',
  getParentRoute: () => rootRouteImport,
} as any)
const UnionRoute = UnionRouteImport.update({
  id: '/union',
  path: '/union',
  getParentRoute: () => rootRouteImport,
} as any)
const SurMesureRoute = SurMesureRouteImport.update({
  id: '/sur-mesure',
  path: '/sur-mesure',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SaveTheDateRoute = SaveTheDateRouteImport.update({
  id: '/save-the-date',
  path: '/save-the-date',
  getParentRoute: () => rootRouteImport,
} as any)
const PortesRoute = PortesRouteImport.update({
  id: '/portes',
  path: '/portes',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresRoute = OffresRouteImport.update({
  id: '/offres',
  path: '/offres',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesRoute = EntreprisesRouteImport.update({
  id: '/entreprises',
  path: '/entreprises',
  getParentRoute: () => rootRouteImport,
} as any)
const EcrinsRoute = EcrinsRouteImport.update({
  id: '/ecrins',
  path: '/ecrins',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurateurRoute = ConfigurateurRouteImport.update({
  id: '/configurateur',
  path: '/configurateur',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparerRoute = ComparerRouteImport.update({
  id: '/comparer',
  path: '/comparer',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaveTheDateIndexRoute = SaveTheDateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SaveTheDateRoute,
} as any)
const StudioSlugRoute = StudioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StudioRoute,
} as any)
const SaveTheDateFormatRoute = SaveTheDateFormatRouteImport.update({
  id: '/$format',
  path: '/$format',
  getParentRoute: () => SaveTheDateRoute,
} as any)
const RsvpTokenRoute = RsvpTokenRouteImport.update({
  id: '/rsvp/$token',
  path: '/rsvp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MaCommandeRefRoute = MaCommandeRefRouteImport.update({
  id: '/ma-commande/$ref',
  path: '/ma-commande/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTokenRoute = LiveTokenRouteImport.update({
  id: '/live/$token',
  path: '/live/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationTokenRoute = InvitationTokenRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieTokenRoute = GalerieTokenRouteImport.update({
  id: '/galerie/$token',
  path: '/galerie/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExperiencesRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMesInvitationsRoute =
  AuthenticatedMesInvitationsRouteImport.update({
    id: '/mes-invitations',
    path: '/mes-invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMesCommandesRoute =
  AuthenticatedMesCommandesRouteImport.update({
    id: '/mes-commandes',
    path: '/mes-commandes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDecorationsRoute =
  AuthenticatedDecorationsRouteImport.update({
    id: '/decorations',
    path: '/decorations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicWeddingRemindersRoute =
  ApiPublicWeddingRemindersRouteImport.update({
    id: '/api/public/wedding-reminders',
    path: '/api/public/wedding-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStatusTransitionRoute =
  ApiPublicStatusTransitionRouteImport.update({
    id: '/api/public/status-transition',
    path: '/api/public/status-transition',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRsvpRemindersRoute = ApiPublicRsvpRemindersRouteImport.update({
  id: '/api/public/rsvp-reminders',
  path: '/api/public/rsvp-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGumroadRoute = ApiPublicGumroadRouteImport.update({
  id: '/api/public/gumroad',
  path: '/api/public/gumroad',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailWorkerRoute = ApiPublicEmailWorkerRouteImport.update({
  id: '/api/public/email-worker',
  path: '/api/public/email-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioIdRoute = AuthenticatedStudioIdRouteImport.update({
  id: '/studio/$id',
  path: '/studio/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminInvitationsRoute =
  AuthenticatedAdminInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommandesRoute =
  AuthenticatedAdminCommandesRouteImport.update({
    id: '/commandes',
    path: '/commandes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminB2bRoute = AuthenticatedAdminB2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAteliersRoute =
  AuthenticatedAdminAteliersRouteImport.update({
    id: '/ateliers',
    path: '/ateliers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedMesInvitationsIdLiveRoute =
  AuthenticatedMesInvitationsIdLiveRouteImport.update({
    id: '/$id/live',
    path: '/$id/live',
    getParentRoute: () => AuthenticatedMesInvitationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/cgv': typeof CgvRoute
  '/comparer': typeof ComparerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/configurateur': typeof ConfigurateurRoute
  '/contact': typeof ContactRoute
  '/ecrins': typeof EcrinsRoute
  '/entreprises': typeof EntreprisesRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/offres': typeof OffresRoute
  '/partenaires': typeof PartenairesRoute
  '/portes': typeof PortesRoute
  '/save-the-date': typeof SaveTheDateRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/sur-mesure': typeof SurMesureRoute
  '/union': typeof UnionRoute
  '/voiles': typeof VoilesRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/decorations': typeof AuthenticatedDecorationsRoute
  '/mes-commandes': typeof AuthenticatedMesCommandesRoute
  '/mes-invitations': typeof AuthenticatedMesInvitationsRouteWithChildren
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/galerie/$token': typeof GalerieTokenRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/live/$token': typeof LiveTokenRoute
  '/ma-commande/$ref': typeof MaCommandeRefRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/save-the-date/$format': typeof SaveTheDateFormatRoute
  '/studio/$slug': typeof StudioSlugRoute
  '/save-the-date/': typeof SaveTheDateIndexRoute
  '/admin/ateliers': typeof AuthenticatedAdminAteliersRoute
  '/admin/b2b': typeof AuthenticatedAdminB2bRoute
  '/admin/commandes': typeof AuthenticatedAdminCommandesRoute
  '/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/studio/$id': typeof AuthenticatedStudioIdRoute
  '/api/public/email-worker': typeof ApiPublicEmailWorkerRoute
  '/api/public/gumroad': typeof ApiPublicGumroadRoute
  '/api/public/rsvp-reminders': typeof ApiPublicRsvpRemindersRoute
  '/api/public/status-transition': typeof ApiPublicStatusTransitionRoute
  '/api/public/wedding-reminders': typeof ApiPublicWeddingRemindersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/mes-invitations/$id/live': typeof AuthenticatedMesInvitationsIdLiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/cgv': typeof CgvRoute
  '/comparer': typeof ComparerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/configurateur': typeof ConfigurateurRoute
  '/contact': typeof ContactRoute
  '/ecrins': typeof EcrinsRoute
  '/entreprises': typeof EntreprisesRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/offres': typeof OffresRoute
  '/partenaires': typeof PartenairesRoute
  '/portes': typeof PortesRoute
  '/studio': typeof StudioRouteWithChildren
  '/sur-mesure': typeof SurMesureRoute
  '/union': typeof UnionRoute
  '/voiles': typeof VoilesRoute
  '/decorations': typeof AuthenticatedDecorationsRoute
  '/mes-commandes': typeof AuthenticatedMesCommandesRoute
  '/mes-invitations': typeof AuthenticatedMesInvitationsRouteWithChildren
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/galerie/$token': typeof GalerieTokenRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/live/$token': typeof LiveTokenRoute
  '/ma-commande/$ref': typeof MaCommandeRefRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/save-the-date/$format': typeof SaveTheDateFormatRoute
  '/studio/$slug': typeof StudioSlugRoute
  '/save-the-date': typeof SaveTheDateIndexRoute
  '/admin/ateliers': typeof AuthenticatedAdminAteliersRoute
  '/admin/b2b': typeof AuthenticatedAdminB2bRoute
  '/admin/commandes': typeof AuthenticatedAdminCommandesRoute
  '/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/studio/$id': typeof AuthenticatedStudioIdRoute
  '/api/public/email-worker': typeof ApiPublicEmailWorkerRoute
  '/api/public/gumroad': typeof ApiPublicGumroadRoute
  '/api/public/rsvp-reminders': typeof ApiPublicRsvpRemindersRoute
  '/api/public/status-transition': typeof ApiPublicStatusTransitionRoute
  '/api/public/wedding-reminders': typeof ApiPublicWeddingRemindersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/mes-invitations/$id/live': typeof AuthenticatedMesInvitationsIdLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/atelier': typeof AtelierRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/cgv': typeof CgvRoute
  '/comparer': typeof ComparerRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/configurateur': typeof ConfigurateurRoute
  '/contact': typeof ContactRoute
  '/ecrins': typeof EcrinsRoute
  '/entreprises': typeof EntreprisesRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/offres': typeof OffresRoute
  '/partenaires': typeof PartenairesRoute
  '/portes': typeof PortesRoute
  '/save-the-date': typeof SaveTheDateRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/sur-mesure': typeof SurMesureRoute
  '/union': typeof UnionRoute
  '/voiles': typeof VoilesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/decorations': typeof AuthenticatedDecorationsRoute
  '/_authenticated/mes-commandes': typeof AuthenticatedMesCommandesRoute
  '/_authenticated/mes-invitations': typeof AuthenticatedMesInvitationsRouteWithChildren
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/galerie/$token': typeof GalerieTokenRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/live/$token': typeof LiveTokenRoute
  '/ma-commande/$ref': typeof MaCommandeRefRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/save-the-date/$format': typeof SaveTheDateFormatRoute
  '/studio/$slug': typeof StudioSlugRoute
  '/save-the-date/': typeof SaveTheDateIndexRoute
  '/_authenticated/admin/ateliers': typeof AuthenticatedAdminAteliersRoute
  '/_authenticated/admin/b2b': typeof AuthenticatedAdminB2bRoute
  '/_authenticated/admin/commandes': typeof AuthenticatedAdminCommandesRoute
  '/_authenticated/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/_authenticated/studio/$id': typeof AuthenticatedStudioIdRoute
  '/api/public/email-worker': typeof ApiPublicEmailWorkerRoute
  '/api/public/gumroad': typeof ApiPublicGumroadRoute
  '/api/public/rsvp-reminders': typeof ApiPublicRsvpRemindersRoute
  '/api/public/status-transition': typeof ApiPublicStatusTransitionRoute
  '/api/public/wedding-reminders': typeof ApiPublicWeddingRemindersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/mes-invitations/$id/live': typeof AuthenticatedMesInvitationsIdLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atelier'
    | '/auth'
    | '/business'
    | '/cgv'
    | '/comparer'
    | '/confidentialite'
    | '/configurateur'
    | '/contact'
    | '/ecrins'
    | '/entreprises'
    | '/experiences'
    | '/faq'
    | '/mentions-legales'
    | '/offres'
    | '/partenaires'
    | '/portes'
    | '/save-the-date'
    | '/studio'
    | '/sur-mesure'
    | '/union'
    | '/voiles'
    | '/admin'
    | '/decorations'
    | '/mes-commandes'
    | '/mes-invitations'
    | '/tableau-de-bord'
    | '/experiences/$slug'
    | '/galerie/$token'
    | '/invitation/$token'
    | '/live/$token'
    | '/ma-commande/$ref'
    | '/rsvp/$token'
    | '/save-the-date/$format'
    | '/studio/$slug'
    | '/save-the-date/'
    | '/admin/ateliers'
    | '/admin/b2b'
    | '/admin/commandes'
    | '/admin/invitations'
    | '/studio/$id'
    | '/api/public/email-worker'
    | '/api/public/gumroad'
    | '/api/public/rsvp-reminders'
    | '/api/public/status-transition'
    | '/api/public/wedding-reminders'
    | '/admin/'
    | '/mes-invitations/$id/live'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atelier'
    | '/auth'
    | '/business'
    | '/cgv'
    | '/comparer'
    | '/confidentialite'
    | '/configurateur'
    | '/contact'
    | '/ecrins'
    | '/entreprises'
    | '/experiences'
    | '/faq'
    | '/mentions-legales'
    | '/offres'
    | '/partenaires'
    | '/portes'
    | '/studio'
    | '/sur-mesure'
    | '/union'
    | '/voiles'
    | '/decorations'
    | '/mes-commandes'
    | '/mes-invitations'
    | '/tableau-de-bord'
    | '/experiences/$slug'
    | '/galerie/$token'
    | '/invitation/$token'
    | '/live/$token'
    | '/ma-commande/$ref'
    | '/rsvp/$token'
    | '/save-the-date/$format'
    | '/studio/$slug'
    | '/save-the-date'
    | '/admin/ateliers'
    | '/admin/b2b'
    | '/admin/commandes'
    | '/admin/invitations'
    | '/studio/$id'
    | '/api/public/email-worker'
    | '/api/public/gumroad'
    | '/api/public/rsvp-reminders'
    | '/api/public/status-transition'
    | '/api/public/wedding-reminders'
    | '/admin'
    | '/mes-invitations/$id/live'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/atelier'
    | '/auth'
    | '/business'
    | '/cgv'
    | '/comparer'
    | '/confidentialite'
    | '/configurateur'
    | '/contact'
    | '/ecrins'
    | '/entreprises'
    | '/experiences'
    | '/faq'
    | '/mentions-legales'
    | '/offres'
    | '/partenaires'
    | '/portes'
    | '/save-the-date'
    | '/studio'
    | '/sur-mesure'
    | '/union'
    | '/voiles'
    | '/_authenticated/admin'
    | '/_authenticated/decorations'
    | '/_authenticated/mes-commandes'
    | '/_authenticated/mes-invitations'
    | '/_authenticated/tableau-de-bord'
    | '/experiences/$slug'
    | '/galerie/$token'
    | '/invitation/$token'
    | '/live/$token'
    | '/ma-commande/$ref'
    | '/rsvp/$token'
    | '/save-the-date/$format'
    | '/studio/$slug'
    | '/save-the-date/'
    | '/_authenticated/admin/ateliers'
    | '/_authenticated/admin/b2b'
    | '/_authenticated/admin/commandes'
    | '/_authenticated/admin/invitations'
    | '/_authenticated/studio/$id'
    | '/api/public/email-worker'
    | '/api/public/gumroad'
    | '/api/public/rsvp-reminders'
    | '/api/public/status-transition'
    | '/api/public/wedding-reminders'
    | '/_authenticated/admin/'
    | '/_authenticated/mes-invitations/$id/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AtelierRoute: typeof AtelierRoute
  AuthRoute: typeof AuthRoute
  BusinessRoute: typeof BusinessRoute
  CgvRoute: typeof CgvRoute
  ComparerRoute: typeof ComparerRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConfigurateurRoute: typeof ConfigurateurRoute
  ContactRoute: typeof ContactRoute
  EcrinsRoute: typeof EcrinsRoute
  EntreprisesRoute: typeof EntreprisesRoute
  ExperiencesRoute: typeof ExperiencesRouteWithChildren
  FaqRoute: typeof FaqRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  OffresRoute: typeof OffresRoute
  PartenairesRoute: typeof PartenairesRoute
  PortesRoute: typeof PortesRoute
  SaveTheDateRoute: typeof SaveTheDateRouteWithChildren
  StudioRoute: typeof StudioRouteWithChildren
  SurMesureRoute: typeof SurMesureRoute
  UnionRoute: typeof UnionRoute
  VoilesRoute: typeof VoilesRoute
  GalerieTokenRoute: typeof GalerieTokenRoute
  InvitationTokenRoute: typeof InvitationTokenRoute
  LiveTokenRoute: typeof LiveTokenRoute
  MaCommandeRefRoute: typeof MaCommandeRefRoute
  RsvpTokenRoute: typeof RsvpTokenRoute
  ApiPublicEmailWorkerRoute: typeof ApiPublicEmailWorkerRoute
  ApiPublicGumroadRoute: typeof ApiPublicGumroadRoute
  ApiPublicRsvpRemindersRoute: typeof ApiPublicRsvpRemindersRoute
  ApiPublicStatusTransitionRoute: typeof ApiPublicStatusTransitionRoute
  ApiPublicWeddingRemindersRoute: typeof ApiPublicWeddingRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voiles': {
      id: '/voiles'
      path: '/voiles'
      fullPath: '/voiles'
      preLoaderRoute: typeof VoilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/union': {
      id: '/union'
      path: '/union'
      fullPath: '/union'
      preLoaderRoute: typeof UnionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sur-mesure': {
      id: '/sur-mesure'
      path: '/sur-mesure'
      fullPath: '/sur-mesure'
      preLoaderRoute: typeof SurMesureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/save-the-date': {
      id: '/save-the-date'
      path: '/save-the-date'
      fullPath: '/save-the-date'
      preLoaderRoute: typeof SaveTheDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portes': {
      id: '/portes'
      path: '/portes'
      fullPath: '/portes'
      preLoaderRoute: typeof PortesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres': {
      id: '/offres'
      path: '/offres'
      fullPath: '/offres'
      preLoaderRoute: typeof OffresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises': {
      id: '/entreprises'
      path: '/entreprises'
      fullPath: '/entreprises'
      preLoaderRoute: typeof EntreprisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecrins': {
      id: '/ecrins'
      path: '/ecrins'
      fullPath: '/ecrins'
      preLoaderRoute: typeof EcrinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurateur': {
      id: '/configurateur'
      path: '/configurateur'
      fullPath: '/configurateur'
      preLoaderRoute: typeof ConfigurateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparer': {
      id: '/comparer'
      path: '/comparer'
      fullPath: '/comparer'
      preLoaderRoute: typeof ComparerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/save-the-date/': {
      id: '/save-the-date/'
      path: '/'
      fullPath: '/save-the-date/'
      preLoaderRoute: typeof SaveTheDateIndexRouteImport
      parentRoute: typeof SaveTheDateRoute
    }
    '/studio/$slug': {
      id: '/studio/$slug'
      path: '/$slug'
      fullPath: '/studio/$slug'
      preLoaderRoute: typeof StudioSlugRouteImport
      parentRoute: typeof StudioRoute
    }
    '/save-the-date/$format': {
      id: '/save-the-date/$format'
      path: '/$format'
      fullPath: '/save-the-date/$format'
      preLoaderRoute: typeof SaveTheDateFormatRouteImport
      parentRoute: typeof SaveTheDateRoute
    }
    '/rsvp/$token': {
      id: '/rsvp/$token'
      path: '/rsvp/$token'
      fullPath: '/rsvp/$token'
      preLoaderRoute: typeof RsvpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ma-commande/$ref': {
      id: '/ma-commande/$ref'
      path: '/ma-commande/$ref'
      fullPath: '/ma-commande/$ref'
      preLoaderRoute: typeof MaCommandeRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$token': {
      id: '/live/$token'
      path: '/live/$token'
      fullPath: '/live/$token'
      preLoaderRoute: typeof LiveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$token': {
      id: '/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof InvitationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie/$token': {
      id: '/galerie/$token'
      path: '/galerie/$token'
      fullPath: '/galerie/$token'
      preLoaderRoute: typeof GalerieTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-invitations': {
      id: '/_authenticated/mes-invitations'
      path: '/mes-invitations'
      fullPath: '/mes-invitations'
      preLoaderRoute: typeof AuthenticatedMesInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-commandes': {
      id: '/_authenticated/mes-commandes'
      path: '/mes-commandes'
      fullPath: '/mes-commandes'
      preLoaderRoute: typeof AuthenticatedMesCommandesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decorations': {
      id: '/_authenticated/decorations'
      path: '/decorations'
      fullPath: '/decorations'
      preLoaderRoute: typeof AuthenticatedDecorationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/wedding-reminders': {
      id: '/api/public/wedding-reminders'
      path: '/api/public/wedding-reminders'
      fullPath: '/api/public/wedding-reminders'
      preLoaderRoute: typeof ApiPublicWeddingRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/status-transition': {
      id: '/api/public/status-transition'
      path: '/api/public/status-transition'
      fullPath: '/api/public/status-transition'
      preLoaderRoute: typeof ApiPublicStatusTransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rsvp-reminders': {
      id: '/api/public/rsvp-reminders'
      path: '/api/public/rsvp-reminders'
      fullPath: '/api/public/rsvp-reminders'
      preLoaderRoute: typeof ApiPublicRsvpRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gumroad': {
      id: '/api/public/gumroad'
      path: '/api/public/gumroad'
      fullPath: '/api/public/gumroad'
      preLoaderRoute: typeof ApiPublicGumroadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-worker': {
      id: '/api/public/email-worker'
      path: '/api/public/email-worker'
      fullPath: '/api/public/email-worker'
      preLoaderRoute: typeof ApiPublicEmailWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio/$id': {
      id: '/_authenticated/studio/$id'
      path: '/studio/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof AuthenticatedStudioIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/invitations': {
      id: '/_authenticated/admin/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AuthenticatedAdminInvitationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/commandes': {
      id: '/_authenticated/admin/commandes'
      path: '/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AuthenticatedAdminCommandesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/b2b': {
      id: '/_authenticated/admin/b2b'
      path: '/b2b'
      fullPath: '/admin/b2b'
      preLoaderRoute: typeof AuthenticatedAdminB2bRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ateliers': {
      id: '/_authenticated/admin/ateliers'
      path: '/ateliers'
      fullPath: '/admin/ateliers'
      preLoaderRoute: typeof AuthenticatedAdminAteliersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/mes-invitations/$id/live': {
      id: '/_authenticated/mes-invitations/$id/live'
      path: '/$id/live'
      fullPath: '/mes-invitations/$id/live'
      preLoaderRoute: typeof AuthenticatedMesInvitationsIdLiveRouteImport
      parentRoute: typeof AuthenticatedMesInvitationsRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAteliersRoute: typeof AuthenticatedAdminAteliersRoute
  AuthenticatedAdminB2bRoute: typeof AuthenticatedAdminB2bRoute
  AuthenticatedAdminCommandesRoute: typeof AuthenticatedAdminCommandesRoute
  AuthenticatedAdminInvitationsRoute: typeof AuthenticatedAdminInvitationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAteliersRoute: AuthenticatedAdminAteliersRoute,
    AuthenticatedAdminB2bRoute: AuthenticatedAdminB2bRoute,
    AuthenticatedAdminCommandesRoute: AuthenticatedAdminCommandesRoute,
    AuthenticatedAdminInvitationsRoute: AuthenticatedAdminInvitationsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedMesInvitationsRouteChildren {
  AuthenticatedMesInvitationsIdLiveRoute: typeof AuthenticatedMesInvitationsIdLiveRoute
}

const AuthenticatedMesInvitationsRouteChildren: AuthenticatedMesInvitationsRouteChildren =
  {
    AuthenticatedMesInvitationsIdLiveRoute:
      AuthenticatedMesInvitationsIdLiveRoute,
  }

const AuthenticatedMesInvitationsRouteWithChildren =
  AuthenticatedMesInvitationsRoute._addFileChildren(
    AuthenticatedMesInvitationsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDecorationsRoute: typeof AuthenticatedDecorationsRoute
  AuthenticatedMesCommandesRoute: typeof AuthenticatedMesCommandesRoute
  AuthenticatedMesInvitationsRoute: typeof AuthenticatedMesInvitationsRouteWithChildren
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedStudioIdRoute: typeof AuthenticatedStudioIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDecorationsRoute: AuthenticatedDecorationsRoute,
  AuthenticatedMesCommandesRoute: AuthenticatedMesCommandesRoute,
  AuthenticatedMesInvitationsRoute:
    AuthenticatedMesInvitationsRouteWithChildren,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedStudioIdRoute: AuthenticatedStudioIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ExperiencesRouteChildren {
  ExperiencesSlugRoute: typeof ExperiencesSlugRoute
}

const ExperiencesRouteChildren: ExperiencesRouteChildren = {
  ExperiencesSlugRoute: ExperiencesSlugRoute,
}

const ExperiencesRouteWithChildren = ExperiencesRoute._addFileChildren(
  ExperiencesRouteChildren,
)

interface SaveTheDateRouteChildren {
  SaveTheDateFormatRoute: typeof SaveTheDateFormatRoute
  SaveTheDateIndexRoute: typeof SaveTheDateIndexRoute
}

const SaveTheDateRouteChildren: SaveTheDateRouteChildren = {
  SaveTheDateFormatRoute: SaveTheDateFormatRoute,
  SaveTheDateIndexRoute: SaveTheDateIndexRoute,
}

const SaveTheDateRouteWithChildren = SaveTheDateRoute._addFileChildren(
  SaveTheDateRouteChildren,
)

interface StudioRouteChildren {
  StudioSlugRoute: typeof StudioSlugRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioSlugRoute: StudioSlugRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AtelierRoute: AtelierRoute,
  AuthRoute: AuthRoute,
  BusinessRoute: BusinessRoute,
  CgvRoute: CgvRoute,
  ComparerRoute: ComparerRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConfigurateurRoute: ConfigurateurRoute,
  ContactRoute: ContactRoute,
  EcrinsRoute: EcrinsRoute,
  EntreprisesRoute: EntreprisesRoute,
  ExperiencesRoute: ExperiencesRouteWithChildren,
  FaqRoute: FaqRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  OffresRoute: OffresRoute,
  PartenairesRoute: PartenairesRoute,
  PortesRoute: PortesRoute,
  SaveTheDateRoute: SaveTheDateRouteWithChildren,
  StudioRoute: StudioRouteWithChildren,
  SurMesureRoute: SurMesureRoute,
  UnionRoute: UnionRoute,
  VoilesRoute: VoilesRoute,
  GalerieTokenRoute: GalerieTokenRoute,
  InvitationTokenRoute: InvitationTokenRoute,
  LiveTokenRoute: LiveTokenRoute,
  MaCommandeRefRoute: MaCommandeRefRoute,
  RsvpTokenRoute: RsvpTokenRoute,
  ApiPublicEmailWorkerRoute: ApiPublicEmailWorkerRoute,
  ApiPublicGumroadRoute: ApiPublicGumroadRoute,
  ApiPublicRsvpRemindersRoute: ApiPublicRsvpRemindersRoute,
  ApiPublicStatusTransitionRoute: ApiPublicStatusTransitionRoute,
  ApiPublicWeddingRemindersRoute: ApiPublicWeddingRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
